# .github/workflows/azure.yml
name: Build and deploy Node.js app to Azure Web App - grokysworld

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build --if-present

      - name: DEBUG - List dist/ contents
        run: |
          echo "=== DIST FOLDER CONTENTS ==="
          if [ -d "dist" ]; then
            ls -R dist/ | head -50
            echo "=== TOTAL FILES: $(find dist/ -type f | wc -l) ==="
          else
            echo "ERROR: dist/ folder not found!"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist/

      - name: DEBUG - Verify downloaded files
        run: |
          echo "=== DOWNLOADED DIST CONTENTS ==="
          ls -R dist/ | head -50

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_363C179D755340EFB62CE989D32F6F16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B12514CE12B4507825D99BFEA283AD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC967F4FFA89452199B0B251152DE82A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: grokysworld
          package: dist/
          # REMOVED: slot-name → now deploys to MAIN site
