name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build
          cp web.config build/web.config
          cp server.cjs build/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_363C179D755340EFB62CE989D32F6F16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B12514CE12B4507825D99BFEA283AD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC967F4FFA89452199B0B251152DE82A }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: grokysworld
          package: build/



